name: prismsync
description: "A gallery app for PhotoPrism for Android"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.8
  photo_manager: ^3.0.0-dev.2
  transparent_image: ^2.0.1
  open_filex: ^4.3.4
  dio: ^5.3.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
